"use client"

import { useState, useEffect, useRef } from "react"
import { useRouter } from "next/navigation"
import { X, Save, Settings, Target, TrendingUp, Shield, ShieldCheck, Zap, Activity, Users, ArrowUpRight, Percent } from "lucide-react"
import { motion, AnimatePresence } from "framer-motion"
import { Button } from "@/components/ui/button"
import { cn } from "@/lib/utils"

interface StrategicConfigurationModalProps {
  isOpen: boolean
  onClose: () => void
  onSaveSuccess?: () => void
  projectId?: string
}

interface CharterData {
  // Layer I: Business Mandate
  businessDriver: string
  metricCategory?: string
  metricOfRecord: string
  baseline: string
  target: string
  
  // Layer II: Marketing Mandate
  operationalPriority: string
  cacCurrent: string
  cacTarget: string
  ltvCurrent: string
  ltvTarget: string
  crCurrent: string
  crTarget: string
  
  // New Fields (Contextual Parity)
  operationalHistorySignal: string
  operationalHistoryNoise: string
  channelEcosystem: string[]

  // System State
  pendingAuthorityRequest?: boolean
}

const METRIC_CATEGORIES = [
  'Financial',
  'Unit economics',
  'Market momentum',
  'Sales'
]

const METRICS_MAP: Record<string, string[]> = {
  'Financial': ['ARR', 'MRR', 'Net profit', 'Gross revenue'],
  'Unit economics': ['LTV', 'CAC', 'LTV:CAC ratio', 'Payback period'],
  'Market momentum': ['Market share %', 'Active users', 'Retention rate %', 'Churn rate %'],
  'Sales': ['Pipeline value', 'Sales velocity', 'Win rate %', 'ACV']
}

const BUSINESS_DRIVERS = [
  { id: 'market_capture', label: 'Market capture', icon: Target },
  { id: 'margin_protection', label: 'Margin protection', icon: Shield },
  { id: 'category_expansion', label: 'Category expansion', icon: ArrowUpRight },
  { id: 'systemic_stabilization', label: 'Systemic stabilization', icon: Activity }
]

const OPERATIONAL_PRIORITIES = [
  { 
    id: 'volume', 
    label: 'Volume', 
    icon: Users, 
    focus: 'Focus: High-funnel lead density.',
    useWhen: 'Use when demand is the bottleneck.',
    copilot: {
      meaning: "System will prioritize Reach & Awareness tactics.",
      anchor: "Metric: Impression Share / CPM"
    }
  },
  { 
    id: 'velocity', 
    label: 'Velocity', 
    icon: Zap, 
    focus: 'Focus: Closing speed.',
    useWhen: 'Use when leads are stuck in pipeline.',
    copilot: {
      meaning: "System will prioritize Conversion & Automation tactics.",
      anchor: "Metric: Sales Cycle Length"
    }
  },
  { 
    id: 'authority', 
    label: 'Authority', 
    icon: Shield, 
    focus: 'Focus: Trust and narrative.',
    useWhen: 'Use when conversion resistance is high.',
    copilot: {
      meaning: "System will prioritize Content & Social Proof tactics.",
      anchor: "Metric: Engagement Rate / Brand Sentiment"
    }
  },
  { 
    id: 'retention', 
    label: 'Retention', 
    icon: Activity, 
    focus: 'Focus: LTV extension.',
    useWhen: 'Use to lower CAC dependency.',
    copilot: {
      meaning: "System will prioritize Lifecycle & Community tactics.",
      anchor: "Metric: LTV / Churn Rate"
    }
  }
]

const TOOLTIPS = {
  cac: "Cost Per Acquisition: The total investment required to win one new customer.",
  ltv: "Lifetime Value: The total revenue generated by a customer over their entire relationship.",
  cr: "The percentage of prospects who complete a desired action."
}

const CHANNEL_ECOSYSTEM = [
  { id: 'paid-search', label: 'Paid search (Google/Bing)' },
  { id: 'paid-social', label: 'Paid social (Meta/LinkedIn)' },
  { id: 'organic-social', label: 'Organic social' },
  { id: 'email-marketing', label: 'Email marketing' },
  { id: 'events-field', label: 'Events and field marketing' },
  { id: 'content-marketing', label: 'Content marketing' },
  { id: 'seo-organic', label: 'SEO and organic search' },
  { id: 'influencer-affiliate', label: 'Influencer and affiliate' }
];

export function StrategicConfigurationModal({ isOpen, onClose, onSaveSuccess, projectId }: StrategicConfigurationModalProps) {
  const router = useRouter()
  const [isSaving, setIsSaving] = useState(false)
  const [activeCategory, setActiveCategory] = useState<string>("")
  const [isCustomMetric, setIsCustomMetric] = useState(false)
  const [data, setData] = useState<CharterData>({
    businessDriver: '',
    metricCategory: '',
    metricOfRecord: '',
    baseline: '',
    target: '',
    operationalPriority: '',
    cacCurrent: '',
    cacTarget: '',
    ltvCurrent: '',
    ltvTarget: '',
    crCurrent: '',
    crTarget: ''
  })

  // Real-Time Collaboration State
  const [partnerActive, setPartnerActive] = useState(false);
  const [authorityLocked, setAuthorityLocked] = useState(false); // Locked for Admin until Client grants
  const [showAuthorityRequest, setShowAuthorityRequest] = useState(false); // For Client to see
  const supabaseRef = useRef<any>(null);
  const channelRef = useRef<any>(null);
  
  // Get user role from local storage or session context (passed down via props or context)
  // For now, we'll infer it or use a prop. Let's assume we can get it from session.
  // Ideally, StrategicConfigurationModal should receive `userRole` as a prop.
  // Since we don't have it in props yet, we'll need to fetch it or rely on parent.
  // Update: We'll modify the props to include userRole.
  
  // Temporary: Fetch session to get role if not provided
  const [userRole, setUserRole] = useState<string>('CLIENT'); // Default to CLIENT for safety
  
  useEffect(() => {
    // Fetch session role
    fetch('/api/auth/session')
      .then(res => res.json())
      .then(session => {
        if (session?.user?.role) {
          setUserRole(session.user.role);
          if (session.user.role !== 'CLIENT') {
             setAuthorityLocked(true); // Admin/Consultant starts locked
          }
        }
      })
      .catch(err => console.error("Session fetch error", err));
  }, []);

  useEffect(() => {
    // Initialize Supabase Realtime
    // Use environment variables for Supabase connection
    const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
    const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
    const projectId = "cml73ju300003vkikvhv32lit"; // Fixed for now, should be dynamic

    if (supabaseUrl && supabaseKey && projectId) {
      // Import dynamically to avoid SSR issues or use the one from AssessmentRunner logic
      import('@supabase/supabase-js').then(({ createClient }) => {
          const supabase = createClient(supabaseUrl, supabaseKey);
          supabaseRef.current = supabase;

          const channel = supabase.channel(`charter:${projectId}`, {
            config: {
              presence: {
                key: userRole,
              },
            },
          });

          channel
            .on('presence', { event: 'sync' }, () => {
              const newState = channel.presenceState();
              const hasClient = Object.keys(newState).some(key => key.includes('CLIENT'));
              const hasConsultant = Object.keys(newState).some(key => key !== 'CLIENT');
              
              if (userRole === 'CLIENT') {
                setPartnerActive(hasConsultant);
              } else {
                setPartnerActive(hasClient);
              }
            })
            .on('broadcast', { event: 'update' }, (payload) => {
              // Receive updates from partner
              if (payload.role !== userRole) {
                 setData(prev => ({ ...prev, ...payload.data }));
              }
            })
            .on('broadcast', { event: 'authority_request' }, (payload) => {
              if (userRole === 'CLIENT') {
                setShowAuthorityRequest(true);
              }
            })
            .on('broadcast', { event: 'authority_grant' }, (payload) => {
              if (userRole !== 'CLIENT') {
                setAuthorityLocked(false);
                // toast("Authority Granted", "You may now confirm the charter.", "success");
              }
            })
            .subscribe(async (status) => {
              if (status === 'SUBSCRIBED') {
                await channel.track({ role: userRole, online_at: new Date().toISOString() });
              }
            });

          channelRef.current = channel;
      });

      return () => {
        if (supabaseRef.current) {
            supabaseRef.current.removeChannel(channelRef.current);
        }
      };
    }
  }, [userRole]);

  // Broadcast updates
  const broadcastUpdate = (newData: Partial<CharterData>) => {
     if (channelRef.current) {
        channelRef.current.send({
           type: 'broadcast',
           event: 'update',
           payload: { role: userRole, data: newData }
        });
     }
     
     // Audit Log
     fetch('/api/strategy-iq/audit', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          eventType: 'CHARTER_UPDATE',
          payload: newData,
          projectId: "cml73ju300003vkikvhv32lit", // Dynamic ID needed
          category: 'CHARTER'
        })
      }).catch(e => console.error(e));
  };

  // Wrap setters to broadcast
  const updateData = (updates: Partial<CharterData> | ((prev: CharterData) => Partial<CharterData>)) => {
      setData(prev => {
          const newData = typeof updates === 'function' ? { ...prev, ...updates(prev) } : { ...prev, ...updates };
          
          // Identify what changed
          const changedKeys: Partial<CharterData> = {};
          (Object.keys(newData) as Array<keyof CharterData>).forEach(key => {
              if (newData[key] !== prev[key]) {
                  changedKeys[key] = newData[key] as any;
              }
          });
          
          if (Object.keys(changedKeys).length > 0) {
              broadcastUpdate(changedKeys);
          }
          
          return newData as CharterData;
      });
  };

  useEffect(() => {
    const saved = localStorage.getItem("lg_strategic_config") || localStorage.getItem("project_context")
    if (saved) {
      try {
        const parsed = JSON.parse(saved)
        // Merge saved data with default structure to ensure all fields exist
        setData(prev => ({ ...prev, ...parsed }))
        
        // Restore category state
        if (parsed.metricCategory) {
          setActiveCategory(parsed.metricCategory)
          // Check if custom
          if (parsed.metricCategory && parsed.metricOfRecord && !METRICS_MAP[parsed.metricCategory]?.includes(parsed.metricOfRecord)) {
            setIsCustomMetric(true)
          }
        } else if (parsed.metricOfRecord) {
          // Backward compatibility: try to find category
          const foundCat = Object.keys(METRICS_MAP).find(cat => 
            METRICS_MAP[cat].includes(parsed.metricOfRecord)
          )
          if (foundCat) {
            setActiveCategory(foundCat)
            setData(prev => ({ ...prev, metricCategory: foundCat }))
          } else if (METRIC_CATEGORIES.includes(parsed.metricOfRecord)) {
             // Old format where metricOfRecord WAS the category
             setActiveCategory(parsed.metricOfRecord)
             setData(prev => ({ ...prev, metricCategory: parsed.metricOfRecord, metricOfRecord: '' }))
          }
        }
      } catch (e) {
        console.error("Failed to parse strategic config", e)
      }
    }
  }, [isOpen])

  const calculateLift = (base: string, target: string) => {
    const b = parseFloat(base)
    const t = parseFloat(target)
    if (!b || !t) return null
    const lift = ((t - b) / b) * 100
    return lift.toFixed(1)
  }

  const calculateReduction = (current: string, target: string) => {
    const c = parseFloat(current)
    const t = parseFloat(target)
    if (!c || !t) return null
    const reduction = ((c - t) / c) * 100
    return reduction.toFixed(1)
  }

  const handleSave = async () => {
    // Task 2: The "ID Anchor" (Frontend State Fix)
    // Ensure we have a valid projectId
    const targetProjectId = projectId; // Ideally passed via props
    
    if (!targetProjectId) {
      console.error("[INTEGRITY_VIOLATION]: Project ID missing from context. Save aborted.");
      alert("System Error: Missing Project Identifier. Please refresh and try again.");
      return;
    }

    if (!data.businessDriver || !data.operationalPriority) {
      alert("Please select both a Business Driver and an Operational Priority.");
      return;
    }

    setIsSaving(true);

    const configData = {
      ...data,
      timestamp: new Date().toISOString(),
      status: 'calibrated'
    };

    // Save to both locations as requested/implied
    localStorage.setItem("lg_strategic_config", JSON.stringify(configData));
    localStorage.setItem("project_context", JSON.stringify(configData));

    // Persist to server to unlock tabs
    console.log("[INTEGRITY_CHECK]: Submitting to Project ID:", targetProjectId);

    try {
        const response = await fetch('/api/project/update-config', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                ...data,
                projectId: targetProjectId
            })
        });

        if (!response.ok) {
           const errorData = await response.json();
           throw new Error(errorData.error || "Server update failed");
        }
        
        // Task 4: Design DNA Enforcement - Success Notification
        // Ideally use toast, but for now we proceed.
        
        // Force refresh to unlock UI
        window.location.reload();
        
    } catch (e) {
        console.error("Failed to save config to server", e);
        alert("Failed to save configuration. Please try again.");
    }

    setTimeout(() => {
      setIsSaving(false)
      if (onSaveSuccess) {
        onSaveSuccess()
      }
      onClose()
    }, 1000)
  }

  const renderMetricInput = (
    label: string, 
    currentKey: keyof CharterData, 
    targetKey: keyof CharterData, 
    isReduction: boolean = false,
    tooltipKey?: keyof typeof TOOLTIPS
  ) => {
    const current = data[currentKey] as string
    const target = data[targetKey] as string
    const percentage = isReduction 
      ? calculateReduction(current, target)
      : calculateLift(current, target)
    
    return (
      <div className="space-y-3 relative group/input">
        <div className="flex items-center gap-2">
          <label className="text-[10px] font-big-shoulders font-bold tracking-[0.2em] text-white/60 uppercase">
            {label}
          </label>
          {tooltipKey && (
            <div className="relative group/tooltip">
              <div className="text-white/20 hover:text-teal transition-colors cursor-help">
                <svg
                  width="10"
                  height="10"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <circle cx="12" cy="12" r="10" />
                  <path d="M12 16v-4" />
                  <path d="M12 8h.01" />
                </svg>
              </div>
              <div className="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 w-48 p-3 rounded-lg bg-[#0A0A0A]/90 backdrop-blur-md border border-teal/20 text-[11px] font-inter text-white/80 shadow-xl opacity-0 invisible group-hover/tooltip:opacity-100 group-hover/tooltip:visible transition-all z-50 pointer-events-none">
                {TOOLTIPS[tooltipKey]}
                <div className="absolute bottom-[-4px] left-1/2 -translate-x-1/2 w-2 h-2 bg-[#0A0A0A]/90 border-r border-b border-teal/20 rotate-45" />
              </div>
            </div>
          )}
        </div>
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-1">
            <span className="text-[9px] text-white/30 tracking-wider">Current</span>
            <input
              type="number"
              value={current}
              onChange={(e) => setData(prev => ({ ...prev, [currentKey]: e.target.value }))}
              className="w-full bg-white/5 border border-white/10 rounded-lg p-3 text-white font-inter focus:border-coral/50 focus:outline-none transition-all"
              placeholder="0.00"
            />
          </div>
          <div className="space-y-1">
            <span className="text-[9px] text-white/30 tracking-wider">Goal</span>
            <input
              type="number"
              value={target}
              onChange={(e) => setData(prev => ({ ...prev, [targetKey]: e.target.value }))}
              className="w-full bg-white/5 border border-white/10 rounded-lg p-3 text-white font-inter focus:border-coral/50 focus:outline-none transition-all"
              placeholder="0.00"
            />
          </div>
        </div>
        {percentage && (
          <div className={cn(
            "text-[10px] font-bold tracking-widest flex items-center gap-2",
            isReduction 
              ? (parseFloat(percentage) > 0 ? "text-emerald-400" : "text-coral")
              : (parseFloat(percentage) > 0 ? "text-emerald-400" : "text-coral")
          )}>
            {isReduction ? (
              <>{percentage}% Reduction required</>
            ) : (
              <>{percentage}% Lift required</>
            )}
          </div>
        )}
      </div>
    )
  }

  const requestAuthority = async () => {
    if (channelRef.current) {
      await channelRef.current.send({
        type: 'broadcast',
        event: 'authority_request',
        payload: { role: userRole },
      });
      // toast("Request Sent", "Waiting for client approval...", "default");
    }
  };

  const grantAuthority = async () => {
    setShowAuthorityRequest(false);
    if (channelRef.current) {
      await channelRef.current.send({
        type: 'broadcast',
        event: 'authority_grant',
        payload: { role: userRole },
      });
      // toast("Authority Granted", "Consultant can now submit.", "success");
    }
  };

  // Authority Handshake Logic
  const handleConfirm = async () => {
    if (userRole === 'CLIENT') {
       if (data.pendingAuthorityRequest) {
          // Client is granting authority
          setShowAuthorityRequest(true); // Re-use modal for final confirmation
       } else {
          // Client submitting directly
          handleSave();
       }
    } else {
       // Admin/Consultant requesting
       if (authorityLocked) {
          requestAuthority();
       } else {
          // Authority already granted
          handleSave();
       }
    }
  };

  return (
    <AnimatePresence>
      {/* ... existing modals ... */}
      
      {/* Footer Update */}
      {isOpen && (
        <div className="fixed inset-0 z-[100] flex items-center justify-end">
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="absolute inset-0 bg-black/60 backdrop-blur-sm"
          />
          
          <motion.div
            initial={{ x: "100%" }}
            animate={{ x: 0 }}
            exit={{ x: "100%" }}
            transition={{ type: "spring", damping: 25, stiffness: 200 }}
            id="calibration-modal"
            className="relative w-full max-w-2xl h-full bg-[#0A0A0A] border-l border-white/10 shadow-2xl flex flex-col"
          >
            {/* Header */}
            <div className="p-4 sm:p-8 border-b border-white/10 flex items-center justify-between bg-white/[0.02]">
              <div className="flex items-center gap-4">
                <div className="w-10 h-10 rounded-xl bg-coral/10 flex items-center justify-center text-coral shrink-0">
                  <Settings size={20} />
                </div>
                <div>
                  <h2 className="text-xl sm:text-3xl font-big-shoulders font-extrabold tracking-widest italic text-white uppercase leading-none mb-1">
                    Strategic charter
                  </h2>
                  <p className="text-[10px] text-white/40 tracking-[0.2em] font-black">
                    Aligning engine logic with your business reality
                  </p>
                </div>
              </div>
              
              <div className="flex items-center gap-4">
                 {/* Presence Indicator */}
                 {partnerActive && (
                    <div className="flex items-center gap-2 px-3 py-1 rounded-full border border-teal/30 bg-teal/5 text-teal animate-pulse">
                      <div className="w-1.5 h-1.5 rounded-full bg-teal" />
                      <span className="text-[9px] font-bold tracking-widest">
                        {userRole === 'CLIENT' ? 'Strategist active' : 'Client active'}
                      </span>
                    </div>
                 )}
                 <button 
                    onClick={onClose}
                    className="w-10 h-10 rounded-full bg-white/5 flex items-center justify-center text-white/40 hover:text-white hover:bg-white/10 transition-all"
                  >
                    <X size={20} />
                  </button>
              </div>
            </div>

            {/* Scrollable Content */}
            <div className="flex-1 overflow-y-auto p-4 sm:p-8 space-y-8 sm:space-y-12 custom-scrollbar">
              
              {/* Layer I: The Business Mandate */}
              <div className="space-y-6">
                <div className="flex items-center gap-3 mb-6">
                  <div className="w-8 h-1 bg-coral rounded-full" />
                  <h3 className="text-lg sm:text-xl font-big-shoulders font-bold text-white uppercase tracking-wider">
                    Layer I: The business mandate
                  </h3>
                </div>

                <div className="space-y-4">
                  <label className="text-[11px] font-big-shoulders font-black tracking-[0.2em] text-white/60 uppercase">
                    Business driver
                  </label>
                  <div className="grid grid-cols-2 gap-3">
                    {BUSINESS_DRIVERS.map((driver) => {
                      const Icon = driver.icon
                      const isSelected = data.businessDriver === driver.id
                      return (
                        <button
                          key={driver.id}
                          onClick={() => updateData({ businessDriver: driver.id })}
                          className={cn(
                            "flex flex-col items-center justify-center p-6 rounded-xl border transition-all gap-3 group",
                            isSelected
                              ? "bg-white/10 border-coral text-white shadow-[0_0_15px_rgba(255,107,107,0.2)]"
                              : "bg-white/5 border-white/5 text-white/40 hover:border-white/10 hover:bg-white/[0.07]"
                          )}
                        >
                          <Icon size={24} className={cn("transition-colors", isSelected ? "text-coral" : "text-white/20 group-hover:text-white/40")} />
                          <span className="text-xs sm:text-lg font-bold tracking-tight font-inter">{driver.label}</span>
                        </button>
                      )
                    })}
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                  <div className="space-y-4">
                  <label className="text-[11px] font-big-shoulders font-black tracking-[0.2em] text-white/60 uppercase">
                    Metric of record
                  </label>
                  
                  {/* Step 1: Category Selection */}
                  <div className="flex flex-wrap gap-2 mb-2">
                    {METRIC_CATEGORIES.map((cat) => (
                      <button
                        key={cat}
                        onClick={() => {
                          setActiveCategory(cat)
                          setIsCustomMetric(false)
                          // Clear metric when switching category to force drill-down
                          if (activeCategory !== cat) {
                            setData(prev => ({ ...prev, metricCategory: cat, metricOfRecord: '' }))
                          } else {
                            setData(prev => ({ ...prev, metricCategory: cat }))
                          }
                        }}
                        className={cn(
                          "px-4 py-2 rounded-lg text-[10px] font-bold tracking-tight font-inter border transition-all",
                          activeCategory === cat
                            ? "bg-coral text-black border-coral"
                            : "bg-transparent border-white/10 text-white/40 hover:border-white/20"
                        )}
                      >
                        {cat}
                      </button>
                    ))}
                  </div>

                  {/* Step 2: Metric Drill-Down */}
                  <AnimatePresence mode="wait">
                    {activeCategory && (
                      <motion.div
                        key={activeCategory}
                        initial={{ opacity: 0, y: -10, height: 0 }}
                        animate={{ opacity: 1, y: 0, height: "auto" }}
                        exit={{ opacity: 0, y: -10, height: 0 }}
                        transition={{ duration: 0.2 }}
                        className="overflow-hidden"
                      >
                        <div className="flex flex-wrap gap-2 p-4 bg-white/[0.02] rounded-xl border border-white/5 mb-2">
                          {METRICS_MAP[activeCategory]?.map(metric => (
                            <button
                              key={metric}
                              onClick={() => {
                                setData(prev => ({ ...prev, metricOfRecord: metric }))
                                setIsCustomMetric(false)
                              }}
                              className={cn(
                                "px-3 py-1.5 rounded-md text-[12px] border transition-all font-medium font-inter tracking-tight",
                                data.metricOfRecord === metric && !isCustomMetric
                                  ? "bg-[#2ED3C6] text-black border-[#2ED3C6]"
                                  : "bg-transparent border-white/15 text-white/60 hover:border-white/30"
                              )}
                            >
                              {metric}
                            </button>
                          ))}
                          
                          {/* Other Button */}
                          <button
                            onClick={() => {
                              setIsCustomMetric(true)
                              updateData({ metricOfRecord: '' })
                            }}
                            className={cn(
                              "px-3 py-1.5 rounded-md text-[12px] border transition-all font-medium font-inter tracking-tight",
                              isCustomMetric
                                ? "bg-[#2ED3C6] text-black border-[#2ED3C6]"
                                : "bg-transparent border-white/15 text-white/60 hover:border-white/30"
                            )}
                          >
                            [ Other + ]
                          </button>
                        </div>
                        
                        {/* Custom Input */}
                        {isCustomMetric && (
                          <motion.div
                            initial={{ opacity: 0 }}
                            animate={{ opacity: 1 }}
                            className="mb-2"
                          >
                            <input 
                              type="text"
                              value={data.metricOfRecord}
                              onChange={(e) => setData(prev => ({ ...prev, metricOfRecord: e.target.value }))}
                              placeholder="Enter custom metric name..."
                              className="w-full bg-white/5 border border-white/10 rounded-lg p-2 text-white text-xs font-inter focus:border-teal/50 focus:outline-none italic"
                              autoFocus
                            />
                          </motion.div>
                        )}
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>

                <div className="space-y-4">
                  <label className="text-[11px] font-big-shoulders font-black tracking-[0.2em] text-white/60 uppercase">
                    Required lift logic <span className="text-teal ml-2">{data.metricOfRecord}</span>
                  </label>
                  <div className="flex flex-col sm:flex-row sm:items-end gap-y-4 gap-x-3">
                    <div className="flex items-end gap-3 flex-1">
                        <div className="flex-1 space-y-1">
                          <span className="text-[9px] text-white/30 tracking-wider">Baseline</span>
                          <input
                            type="number"
                            value={data.baseline}
                            onChange={(e) => updateData({ baseline: e.target.value })}
                            className="w-full bg-white/5 border border-white/10 rounded-lg p-3 text-white font-serif italic focus:border-coral/50 focus:outline-none transition-all"
                            placeholder="0"
                          />
                        </div>
                        <div className="pb-3 text-white/20">→</div>
                        <div className="flex-1 space-y-1">
                          <span className="text-[9px] text-white/30 tracking-wider">Target</span>
                          <input
                            type="number"
                            value={data.target}
                            onChange={(e) => updateData({ target: e.target.value })}
                            className="w-full bg-white/5 border border-white/10 rounded-lg p-3 text-white font-serif italic focus:border-coral/50 focus:outline-none transition-all"
                            placeholder="0"
                          />
                        </div>
                    </div>
                    {data.baseline && data.target && (
                        <div className="text-left sm:text-right pt-2 sm:pt-0">
                          <span className="text-emerald-400 font-bold font-big-shoulders text-lg tracking-widest block sm:inline">
                            +{calculateLift(data.baseline, data.target)}% Lift {data.metricOfRecord ? `in ${data.metricOfRecord}` : ''}
                          </span>
                        </div>
                    )}
                  </div>
                </div>
                </div>
              </div>

              {/* Layer II: The Marketing Mandate */}
              <div className="space-y-6">
                <div className="flex items-center gap-3 mb-6 pt-6 border-t border-white/5">
                  <div className="w-8 h-1 bg-teal rounded-full" />
                  <h3 className="text-lg sm:text-xl font-big-shoulders font-bold text-white uppercase tracking-wider">
                    Layer II: The marketing mandate
                  </h3>
                </div>

                <div className="space-y-4">
                  <label className="text-[11px] font-big-shoulders font-black tracking-[0.2em] text-white/60 uppercase">
                    Operational priority
                  </label>
                  <div className="grid grid-cols-2 gap-3">
                    {OPERATIONAL_PRIORITIES.map((priority) => {
                      const Icon = priority.icon
                      const isSelected = data.operationalPriority === priority.id
                      return (
                        <button
                          key={priority.id}
                          onClick={() => setData(prev => ({ ...prev, operationalPriority: priority.id }))}
                          className={cn(
                            "flex flex-col items-center justify-center p-6 rounded-xl border transition-all gap-3 group relative overflow-hidden",
                            isSelected
                              ? "bg-white/10 border-teal text-white shadow-[0_0_15px_rgba(20,184,166,0.2)]"
                              : "bg-white/5 border-white/5 text-white/40 hover:border-white/10 hover:bg-white/[0.07]"
                          )}
                        >
                          <Icon size={24} className={cn("transition-colors mb-1", isSelected ? "text-teal" : "text-white/20 group-hover:text-white/40")} />
                          <span className="text-lg font-bold tracking-tight font-inter">{priority.label}</span>
                          <div className={cn(
                            "text-[10px] sm:text-xs font-inter opacity-60 text-center leading-tight mt-1 space-y-1",
                            isSelected ? "text-white" : "text-white/40"
                          )}>
                            <p>{priority.focus}</p>
                            <p className="italic">{priority.useWhen}</p>
                          </div>
                          
                          {/* Consultant Copilot HUD Overlay (Only visible when selected) */}
                          {isSelected && priority.copilot && userRole !== 'CLIENT' && (
                             <motion.div 
                               initial={{ opacity: 0, y: 10 }}
                               animate={{ opacity: 1, y: 0 }}
                               className="absolute inset-0 bg-black/95 flex flex-col items-center justify-center p-4 text-center z-10"
                             >
                               <div className="text-[9px] tracking-widest text-teal mb-2">Consultant copilot</div>
                               <p className="text-[11px] text-white/60 mb-2 leading-tight">
                                 {priority.copilot.meaning}
                               </p>
                               <p className="font-serif italic text-white text-sm leading-tight">
                                 {priority.copilot.anchor}
                               </p>
                             </motion.div>
                          )}
                        </button>
                      )
                    })}
                  </div>
                </div>

                <div className="space-y-4">
                  <label className="text-[11px] font-big-shoulders font-black tracking-[0.2em] text-white/60 uppercase mb-4 block">
                    Performance benchmarks
                  </label>
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-6 bg-white/[0.02] p-6 rounded-xl border border-white/5">
                    {renderMetricInput("CAC Efficiency", "cacCurrent", "cacTarget", true, "cac")}
                    {renderMetricInput("LTV Growth", "ltvCurrent", "ltvTarget", false, "ltv")}
                    {renderMetricInput("Conversion Rate", "crCurrent", "crTarget", false, "cr")}
                  </div>
                  <div className="pt-2 border-t border-white/5 mt-4">
                    <p className="text-[10px] font-mono text-white/30 tracking-wide text-center">
                      // ADVISORY NOTE: The system calculates the LTV:CAC ratio to determine the risk level of your current growth model. An 3:1 ratio is the benchmark for institutional stability.
                    </p>
                  </div>
                </div>

                {/* OPERATIONAL HISTORY (Signal vs Noise) */}
                <div className="space-y-4">
                   <label className="text-[11px] font-big-shoulders font-black tracking-[0.2em] text-white/60 uppercase">
                      Operational history
                   </label>
                   <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                      <div className="space-y-2">
                         <span className="text-[9px] text-emerald-400/80 tracking-wider font-bold">Reliable signal (What works)</span>
                         <textarea
                            value={data.operationalHistorySignal}
                            onChange={(e) => updateData({ operationalHistorySignal: e.target.value })}
                            className="w-full bg-white/5 border border-white/10 rounded-lg p-3 text-white text-xs font-inter leading-relaxed focus:border-teal/50 focus:outline-none transition-all h-24 resize-none"
                            placeholder="e.g. High-intent search, LinkedIn prospecting..."
                         />
                      </div>
                      <div className="space-y-2">
                         <span className="text-[9px] text-coral/80 tracking-wider font-bold">Strategic noise (What failed)</span>
                         <textarea
                            value={data.operationalHistoryNoise}
                            onChange={(e) => updateData({ operationalHistoryNoise: e.target.value })}
                            className="w-full bg-white/5 border border-white/10 rounded-lg p-3 text-white text-xs font-inter leading-relaxed focus:border-coral/50 focus:outline-none transition-all h-24 resize-none"
                            placeholder="e.g. Broad targeting on Meta, Cold email blasts..."
                         />
                      </div>
                   </div>
                </div>

                {/* CHANNEL ECOSYSTEM */}
                <div className="space-y-4">
                   <label className="text-[11px] font-big-shoulders font-black tracking-[0.2em] text-white/60 uppercase">
                      Channel ecosystem
                   </label>
                   <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                      {CHANNEL_ECOSYSTEM.map(channel => {
                         const isSelected = data.channelEcosystem?.includes(channel.id);
                         return (
                            <button
                               key={channel.id}
                               onClick={() => {
                                  const current = data.channelEcosystem || [];
                                  const newChannels = current.includes(channel.id) 
                                     ? current.filter(c => c !== channel.id)
                                     : [...current, channel.id];
                                  updateData({ channelEcosystem: newChannels });
                               }}
                               className={cn(
                                  "px-4 py-3 rounded-lg text-[10px] font-bold tracking-tight font-inter border transition-all text-center leading-tight",
                                  isSelected
                                     ? "bg-white/10 border-teal text-white shadow-[0_0_10px_rgba(20,184,166,0.15)]"
                                     : "bg-white/5 border-white/5 text-white/40 hover:border-white/10 hover:bg-white/[0.07]"
                               )}
                            >
                               {channel.label}
                            </button>
                         )
                      })}
                   </div>
                </div>

              </div>

            </div>

      <div className="p-4 sm:p-8 border-t border-white/10 bg-white/[0.01] flex items-center justify-between gap-4 sticky bottom-0 z-20 backdrop-blur-md bg-[#0A0A0A]/90 sm:static sm:bg-transparent sm:backdrop-blur-none">
              
        {/* Admin Authority Request */}
        {userRole !== 'CLIENT' && authorityLocked && (
          <Button
              onClick={requestAuthority}
              variant="outline"
              className="w-full font-bold tracking-tight py-6 rounded-xl transition-all shadow-lg text-lg font-inter border-coral/30 text-coral hover:bg-coral/10"
          >
              <div className="flex items-center gap-2">
                <Settings size={20} className="mr-2" />
                Request authority to submit
              </div>
          </Button>
        )}

        {/* Client Grant Authority (if pending) */}
        {userRole === 'CLIENT' && data.pendingAuthorityRequest && (
           <Button
              onClick={() => setShowAuthorityRequest(true)}
              className="w-full font-bold tracking-tight py-6 rounded-xl transition-all shadow-lg text-lg font-inter bg-coral hover:bg-coral/90 text-black shadow-coral/20 animate-pulse"
           >
              <div className="flex items-center gap-2">
                <ShieldCheck size={20} className="mr-2" />
                Grant pending authority request
              </div>
           </Button>
        )}

        {/* Standard Save (Client or Unlocked Admin) */}
        {((userRole === 'CLIENT' && !data.pendingAuthorityRequest) || (!authorityLocked && userRole !== 'CLIENT')) && (
          <Button
            id="btn-save-config"
            onClick={handleSave}
            disabled={isSaving}
            className={cn(
              "w-full font-bold tracking-tight py-4 sm:py-6 rounded-xl transition-all shadow-lg group text-base sm:text-lg font-inter min-h-[48px]",
              isSaving 
                ? "bg-[#1BA6A6] text-white shadow-teal-900/20" 
                : "bg-coral hover:bg-coral/90 text-black shadow-coral/20"
            )}
          >
            {isSaving ? (
              <>Calibrating engine...</>
            ) : (
              <>
                <ShieldCheck size={20} className="mr-2 group-hover:scale-110 transition-transform" />
                Confirm mandates // Lock strategic record
              </>
            )}
          </Button>
        )}
      </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  )
}
