[build]
  publish = "."
  command = "ls -la && echo 'Force rebuild - Card game fix deployed - $(date)'"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/case-study-free-to-be-free"
  to = "/case-study-free-to-be-free.html"
  status = 200

[[redirects]]
  from = "/case-study-fsa"
  to = "/case-study-fsa.html"
  status = 200

[[redirects]]
  from = "/case-study-teams-final-dm"
  to = "/case-study-teams-final-dm.html"
  status = 200

[[redirects]]
  from = "/case-study-ai-browsing"
  to = "/case-study-ai-browsing.html"
  status = 200

[[redirects]]
  from = "/case-study-edge-ucational"
  to = "/case-study-edge-ucational.html"
  status = 200

[[redirects]]
  from = "/caseStudy-edge-mobile"
  to = "/caseStudy_edge_mobile.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/cv"
  to = "/cv.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact-clean.html"
  status = 200

[[redirects]]
  from = "/timeline"
  to = "/timeline.html"
  status = 200

[[redirects]]
  from = "/experience"
  to = "/myexperience.html"
  status = 200

[[redirects]]
  from = "/thoughts"
  to = "/thoughts/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"