name = "creative-portal"
main = ".open-next/worker.js"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# For Pages static deployments from the repository root
pages_build_output_dir = "deploy"
