"""Prove APPLY pipeline: set obvious pilot crops, approve, write CSS."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(".")
CASE = ROOT / "studio/case-studies/criar-sin-culpas"
MANIFEST = CASE / "csc-case-study-image-manifest.json"
APPLIED = CASE / "csc-crops-applied.css"

PILOTS = {
    "starting-point__start-portrait__01": {
        "desktop": {"fit": "cover", "x": 72, "y": 22, "zoom": 1.35, "scaleX": 1, "scaleY": 1},
        "tablet": {"fit": "cover", "x": 68, "y": 28, "zoom": 1.25, "scaleX": 1, "scaleY": 1},
        "mobile": {"fit": "cover", "x": 64, "y": 30, "zoom": 1.45, "scaleX": 1, "scaleY": 1},
    },
    "reader-state__artifact__14": {
        "desktop": {"fit": "cover", "x": 18, "y": 8, "zoom": 1.55, "scaleX": 1, "scaleY": 1},
        "tablet": {"fit": "cover", "x": 22, "y": 12, "zoom": 1.4, "scaleX": 1, "scaleY": 1},
        "mobile": {"fit": "cover", "x": 30, "y": 10, "zoom": 1.65, "scaleX": 1, "scaleY": 1},
    },
    "visual-languages__illustration-ladder__17": {
        "desktop": {"fit": "contain", "x": 50, "y": 40, "zoom": 1.2, "scaleX": 1, "scaleY": 1},
        "tablet": {"fit": "contain", "x": 50, "y": 45, "zoom": 1.15, "scaleX": 1, "scaleY": 1},
        "mobile": {"fit": "contain", "x": 50, "y": 50, "zoom": 1.1, "scaleX": 1, "scaleY": 1},
    },
}

m = json.loads(MANIFEST.read_text(encoding="utf-8"))
# Keep previously approved non-pilots if any, but force pilot proof crops
for inst in m["instances"]:
    if inst["id"] in PILOTS:
        inst["crops"] = PILOTS[inst["id"]]
        inst["approved"] = True
        inst["status"] = "APPROVED"
        inst["pilot"] = True

MANIFEST.write_text(json.dumps(m, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

lines = [
    "/* Auto-generated by CSC Image Director — approved crops only */",
    "/* Fallback for no-JS. Runtime binder reads the manifest. */",
    "",
]
approved = [i for i in m["instances"] if i.get("approved")]
for inst in approved:
    crops = inst.get("crops") or {}
    sel = f'[data-csc-img="{inst["id"]}"]'
    for bp in ("desktop", "tablet", "mobile"):
        c = crops.get(bp) or {"fit": "cover", "x": 50, "y": 50, "zoom": 1, "scaleX": 1, "scaleY": 1}
        # vars written once below
        crops[bp] = c
    d, t, mob = crops["desktop"], crops["tablet"], crops["mobile"]
    lines.append(f"{sel} {{")
    for bp, c in (("desktop", d), ("tablet", t), ("mobile", mob)):
        lines.append(f"  --crop-fit-{bp}: {c['fit']};")
        lines.append(f"  --crop-x-{bp}: {float(c['x']):.2f}%;")
        lines.append(f"  --crop-y-{bp}: {float(c['y']):.2f}%;")
        lines.append(f"  --crop-zoom-{bp}: {float(c['zoom']):.4f};")
        lines.append(f"  --crop-sx-{bp}: {float(c['scaleX']):.4f};")
        lines.append(f"  --crop-sy-{bp}: {float(c['scaleY']):.4f};")
    lines.append("}")
    lines.append(f"{sel} {{")
    lines.append("  object-fit: var(--crop-fit-desktop, cover) !important;")
    lines.append("  object-position: var(--crop-x-desktop, 50%) var(--crop-y-desktop, 50%) !important;")
    lines.append("  transform: scale(calc(var(--crop-zoom-desktop, 1) * var(--crop-sx-desktop, 1)), calc(var(--crop-zoom-desktop, 1) * var(--crop-sy-desktop, 1))) !important;")
    lines.append("  transform-origin: var(--crop-x-desktop, 50%) var(--crop-y-desktop, 50%) !important;")
    lines.append("}")
    lines.append("@media (max-width: 1100px) {")
    lines.append(f"  {sel} {{")
    lines.append("    object-fit: var(--crop-fit-tablet, var(--crop-fit-desktop, cover)) !important;")
    lines.append("    object-position: var(--crop-x-tablet, 50%) var(--crop-y-tablet, 50%) !important;")
    lines.append("    transform: scale(calc(var(--crop-zoom-tablet, 1) * var(--crop-sx-tablet, 1)), calc(var(--crop-zoom-tablet, 1) * var(--crop-sy-tablet, 1))) !important;")
    lines.append("    transform-origin: var(--crop-x-tablet, 50%) var(--crop-y-tablet, 50%) !important;")
    lines.append("  }")
    lines.append("}")
    lines.append("@media (max-width: 820px) {")
    lines.append(f"  {sel} {{")
    lines.append("    object-fit: var(--crop-fit-mobile, var(--crop-fit-desktop, cover)) !important;")
    lines.append("    object-position: var(--crop-x-mobile, 50%) var(--crop-y-mobile, 50%) !important;")
    lines.append("    transform: scale(calc(var(--crop-zoom-mobile, 1) * var(--crop-sx-mobile, 1)), calc(var(--crop-zoom-mobile, 1) * var(--crop-sy-mobile, 1))) !important;")
    lines.append("    transform-origin: var(--crop-x-mobile, 50%) var(--crop-y-mobile, 50%) !important;")
    lines.append("  }")
    lines.append("}")
    lines.append("")

APPLIED.write_text("\n".join(lines), encoding="utf-8")
print(f"approved={len(approved)}")
print("pilots wired:")
for pid in PILOTS:
    print(" ", pid, PILOTS[pid]["desktop"])
